site_name: Портфолио | Коляда Дарья
site_description: Персональный сайт с отчетами по лабораторным работам
site_author: Коляда Дарья

nav:
  - Главная: index.md
  - Лабораторные работы:
    - Обзор работ: labs/index.md
    - 1 курс 2025 год:
      - Лабораторная №1: labs/1year_2025/lab1_2025.md
      - Лабораторная №2: labs/1year_2025/lab2_2025.md
      - Лабораторная №3: labs/1year_2025/lab3_2025.md
      - Лабораторная №4: labs/1year_2025/lab4_2025.md
      - Лабораторная №5: labs/1year_2025/lab5_2025.md
      - Лабораторная №6: labs/1year_2025/lab6_2025.md
      - Лабораторная №7: labs/1year_2025/lab7_2025.md
      - Лабораторная №8: labs/1year_2025/lab8_2025.md
      - Лабораторная №9: labs/1year_2025/lab9_2025.md
      - Лабораторная №10: labs/1year_2025/lab10_2025.md
      - Лабораторная №11: labs/1year_2025/lab11_2025.md
    - 1 курс 2026 год:
      - Лабораторная №1: labs/1year_2026/lab1_2026.md
      - Лабораторная №2: labs/1year_2026/lab2_2026.md
  - Об авторе: about.md

extra_css:
  - assets/stylesheets/my_design.css

theme:
  name: material
  language: ru           # Чтобы поиск и интерфейс были на русском
  palette:
    # Настройка для светлой темы
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom    # Указываем custom, чтобы работали цвета из CSS
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Перейти на темную тему

    # Настройка для темной темы
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Перейти на светлую тему
#  features:
#    - navigation.tabs # Горизонтальное меню сверху


markdown_extensions:
  - admonition             # Цветные блоки
  - pymdownx.details       # Раскрывающиеся списки
  - pymdownx.superfences   # Для вложенности кода в спойлеры
  - pymdownx.arithmatex    # Для отображения математических формул
  - attr_list              # Управление оформлением
  - pymdownx.highlight:    # Подсветка кода
      pygments_lang_class: true  # Для раскраски кода
  - pymdownx.inlinehilite  # Подсветка кода внутри предложений


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kolyada-daria