site_name: Портфолио | Коляда Дарья
site_description: Персональный сайт с отчетами по лабораторным работам
site_author: Коляда Дарья

nav:
  - Главная: index.md
  - Лабораторные работы:
    - Обзор работ: labs/index.md
    - 1 семестр:
      - Лабораторная №1: labs/sem1/lab1_sem1.md
      - Лабораторная №2: labs/sem1/lab2_sem1.md
      - Лабораторная №3: labs/sem1/lab3_sem1.md
      - Лабораторная №4: labs/sem1/lab4_sem1.md
      - Лабораторная №5: labs/sem1/lab5_sem1.md
      - Лабораторная №6: labs/sem1/lab6_sem1.md
      - Лабораторная №7: labs/sem1/lab7_sem1.md
      - Лабораторная №8: labs/sem1/lab8_sem1.md
      - Лабораторная №9: labs/sem1/lab9_sem1.md
      - Лабораторная №10: labs/sem1/lab10_sem1.md
      - Лабораторная №11: labs/sem1/lab11_sem1.md
    - 2 семестр:
      - Лабораторная №1: labs/sem2/lab1_sem2.md
      - Лабораторная №2: labs/sem2/lab2_sem2.md
      - Лабораторная №3: labs/sem2/lab3_sem2.md
      - Лабораторная №4: labs/sem2/lab4_sem2.md
      - Лабораторная №5: labs/sem2/lab5_sem2.md
      - Лабораторная №6: labs/sem2/lab6_sem2.md
  - Об авторе: about.md

extra_css:
  - assets/stylesheets/my_design.css

theme:
  name: material
  language: ru           # Чтобы поиск и интерфейс были на русском
  palette:
    # Настройка для светлой темы
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom    # Указываем custom, чтобы работали цвета из CSS
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Перейти на темную тему

    # Настройка для темной темы
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Перейти на светлую тему
#  features:
#    - navigation.tabs # Горизонтальное меню сверху


markdown_extensions:
  - admonition             # Цветные блоки
  - pymdownx.details       # Раскрывающиеся списки
  - pymdownx.superfences   # Для вложенности кода в спойлеры
  - pymdownx.arithmatex    # Для отображения математических формул
  - attr_list              # Управление оформлением
  - pymdownx.highlight:    # Подсветка кода
      pygments_lang_class: true  # Для раскраски кода
  - pymdownx.inlinehilite  # Подсветка кода внутри предложений


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kolyada-daria